// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	_ "github.com/jackc/pgconn"
	_ "github.com/jackc/pgx/v4"
)

// Injectors from wire.go:

func InitService() (serviceRegistry, error) {
	diDbConnRegistry, err := providerDbConnRegistry()
	if err != nil {
		return serviceRegistry{}, err
	}
	diRepositoryRegistry := provideRepositoryRegistry(diDbConnRegistry)
	diServiceRegistry := provideServiceRegistry(diRepositoryRegistry)
	return diServiceRegistry, nil
}
