// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package chat_db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Character struct {
	ID   int64
	Name string
	Bio  string
	Note sql.NullString
}

type User struct {
	ID        uuid.UUID
	LoginName string
}

type UserLoginWithEmailPassword struct {
	ID           int64
	UserID       uuid.UUID
	Email        string
	PasswordHash string
}
